apiVersion: v1
kind: Service
metadata:
  name: llm-web-service
  namespace: llm
  labels:
    app: llm-web
spec:
  type: ClusterIP
  selector:
    app: llm-web
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP

