apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  applicationsAPIKind: argocd
  argocd.server: argocd-server.argocd.svc.cluster.local
  argocd.insecure: "true"

  # ðŸ‘‡ å…³é”®
  dryRun: "false"

  interval: 2m
  log.level: info
