apiVersion: v1
kind: Service
metadata:
  name: bert-worker-service
  namespace: llm
spec:
  selector:
    app: bert-worker
  type: ClusterIP
  ports:
    - name: http
      port: 8001
      targetPort: 8001    # 你的 BERT worker 容器监听的端口
      protocol: TCP

