apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dcgm-exporter-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://nvidia.github.io/dcgm-exporter/helm-charts
    chart: dcgm-exporter
    targetRevision: 3.3.0
    helm:
      valueFiles:
        - $values/helm/monitoring/dcgm/values.yaml
      # 或者直接从 Git 仓库读取（推荐）
      # valueFiles:
      #   - https://raw.githubusercontent.com/Johnny-dai-git/llm-deployment/main/helm/monitoring/dcgm/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
