apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: llm-ip-pool
  namespace: metallb-system
spec:
  addresses:
    - VIRTUAL_IP/32   # system node 的公网 IP

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: llm-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - llm-ip-pool
