apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: llm-ip-pool
  namespace: metallb-system
spec:
  addresses:
    # TODO: Configure your MetalLB IP pool range here
    # Example: - 192.168.1.200-192.168.1.250
    # Or: - 10.0.0.100/32
    - 192.168.1.200-192.168.1.250

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: llm-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - llm-ip-pool
