name: Local Test

on:
  push:
    branches: [ "main" ]

jobs:
  test-self-hosted:
    runs-on: self-hosted   # 用你刚刚配置的本地 runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show working dir
        run: |
          echo "Running on self-hosted runner"
          pwd
          ls

